# Generated by Django 4.2.2 on 2023-07-02 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidoCliente',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombreCliente',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='master.perfilusuario'),
            preserve_default=False,
        ),
    ]
