# Generated by Django 4.2.2 on 2023-07-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_rename_apellidocliente_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenProducto',
            field=models.FileField(default=1, max_length=200, upload_to='productos'),
            preserve_default=False,
        ),
    ]
